(ns totalisator.repository.queries
  (:require [yesql.core :refer [defqueries]]
            [totalisator.context.context :as c]
            [camel-snake-kebab.core :refer [->kebab-case-keyword ->snake_case_keyword]]
            [camel-snake-kebab.extras :refer [transform-keys]]))

(defqueries "queries/users.sql" )
(defqueries "queries/totalisators.sql")
(defqueries "queries/teams.sql")
(defqueries "queries/winner_bets.sql")
(defqueries "queries/match_bets.sql")
(defqueries "queries/matches.sql")

(defn- db-spec [] {:connection (:connection-uri @c/db-configuration)})
(defn- ->kebab-case [map] (transform-keys ->kebab-case-keyword map))
(defn- ->snake-case [map] (transform-keys ->snake_case_keyword map))

(defn query
  ;yesql design issue. empty map not supported
  ([get-fn] (query get-fn {}))
  ([get-fn parameters] (map ->kebab-case (get-fn (->snake-case parameters) (db-spec)))))

(defn query-single [get-fn parameters]
  (first (query get-fn parameters)))

(defn update<! [update-fn data]
  (update-fn (->snake-case data) (db-spec))
  data)

(defn insert<! [insert-fn data]
  "Performs insert and returns data with autogenerated :id"
  (assoc data :id (first (vals (insert-fn (->snake-case data) (db-spec))))))

(defn insert-or-update! [insert-fn update-fn data]
  (if (:id data)
    (update<! update-fn data)
    (insert<! insert-fn data)))
